# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - CatacombStudios

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Build the server project
      - name: Build server
        run: dotnet build CatacombApp.Server/CatacombApp.Server.csproj --configuration Release

      # Publish the server project
      - name: Publish server
        run: dotnet publish CatacombApp.Server/CatacombApp.Server.csproj -c Release -o ./publish
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}

      # Install dependencies and build the Angular client
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install client dependencies
        run: |
          cd catacombapp.client
          npm install

      - name: Build client
        run: |
          cd catacombapp.client
          npm run build --prod

      # Copy Angular build output to server's wwwroot
      - name: Copy Angular build to wwwroot
        run: |
          if (-Not (Test-Path ./publish/wwwroot)) { mkdir ./publish/wwwroot }
          cp -r catacombapp.client/dist/catacombapp.client/* ./publish/wwwroot
          ls ./publish/wwwroot

      # Upload artifacts for deployment
      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: ${{env.DOTNET_ROOT}}/server

      - name: Upload client artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: catacombapp.client/dist/catacombapp.client

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download server artifact
        uses: actions/download-artifact@v4
        with:
          name: server

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D57CAA604B041AB913621B95A993D19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A0A23DE2ED124995B6F7A471B4054CD7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E21CAE9963CC4A03B5D96935FD4593C6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CatacombStudios'
          slot-name: 'Production'
          package: .
